//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_pc
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string action { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual User User { get; set; }
    }
}
